project_id = "pqhiyqresnjiktkyjshh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[rest]
enabled = true
port = 54329

[realtime]
enabled = true
port = 54330

[edge_runtime]
enabled = true
port = 54331

[analytics]
enabled = false

[functions.appointment-reminders]
verify_jwt = true

[functions.check-reminder-limit]
verify_jwt = true

[functions.check-subscription-status]
verify_jwt = true

[functions.cleanup-subscriptions]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create_update_goal_amount_function]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-html]
verify_jwt = false

[functions.generate-pwa-manifest]
verify_jwt = false

[functions.get-admin-settings]
verify_jwt = true

[functions.get-analytics-data]
verify_jwt = true

[functions.get-churn-analysis]
verify_jwt = true

[functions.get-customers-data]
verify_jwt = true

[functions.get-plan-analytics]
verify_jwt = true

[functions.get-public-settings]
verify_jwt = false

[functions.get-reminder-stats]
verify_jwt = true

[functions.get-stripe-prices]
verify_jwt = true

[functions.grant-admin-access]
verify_jwt = true

[functions.migrate-settings]
verify_jwt = true

[functions.promote-to-admin]
verify_jwt = false

[functions.recover-purchases]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-subscriptions]
verify_jwt = false

[functions.update-admin-email]
verify_jwt = true

[functions.update-admin-settings]
verify_jwt = true

[functions.update-plan-config]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.update_goal_amount]
verify_jwt = true

[functions.verify-admin-access]
verify_jwt = true