// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsuhvhflwobsdtftihfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zdWh2aGZsd29ic2R0ZnRpaGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTMxNDMsImV4cCI6MjA3MTcyOTE0M30.nTx8-qyRWDxKv2QSlAm1ekVyHsKv_4kqwnerijDl9G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});