// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqhiyqresnjiktkyjshh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxaGl5cXJlc25qaWt0a3lqc2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDE4NjgsImV4cCI6MjA3MTg3Nzg2OH0.xLNsCPWyyzqcd0uv-Z7q_slJ8Hh1Ac7iQuf-U_vNM_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});